### ISSUE TITLE
OneDriveLib.dll is not loading

### ISSUE THREAD

**Issue by ukreddy-erwin** [rodneyviana/ODSyncService#1]
Below is the output we are getting on every system.
Even if we install onedrive client or not.

PS C:\Users\uday-\Downloads\New folder> Import-Module Powershell\OneDriveLib.dll
Import-Module : The specified module 'Powershell\OneDriveLib.dll' was not loaded because no valid module file was
found in any module directory.
At line:1 char:1
+ Import-Module Powershell\OneDriveLib.dll
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Powershell\OneDriveLib.dll:String) [Import-Module], FileNotFoundEx
   ception
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

PS C:\Users\uday-\Downloads\New folder> Import-Module .\ODNative.dll
Import-Module : Could not load file or assembly 'file:///C:\Users\uday-\Downloads\New folder\ODNative.dll' or one of
its dependencies. The module was expected to contain an assembly manifest.
At line:1 char:1
+ Import-Module .\ODNative.dll
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], BadImageFormatException
    + FullyQualifiedErrorId : System.BadImageFormatException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by rodneyviana** [comment]
Right-click on the DLL and choose 'Unblock' and click 'Ok'
Your environment may have a policy blocking what is downloaded from Internet and does not contain a digital signature.

See a screenshot here: https://blogs.msdn.microsoft.com/rodneyviana/2017/08/30/tool-to-generate-debugdiag-rule-for-sharepoint-based-on-event-id-tag-and-optionally-a-partial-message/

**Comment by richahl** [comment]
I got the same error when trying to load the module, but since I didn't have the unblock option under properties I had to download streams.exe from MS and remove the ntfs stream before it worked.

**Comment by VertigoRay** [comment]
You can also use PowerShell's [`Unblock-File`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file) function.

Why is this still open? :)
