### ISSUE TITLE
Showing as Syncing even UptoDate

### ISSUE THREAD

**Issue by ukreddy-erwin** [rodneyviana/ODSyncService#11]
Server 2012 R2 OS.
Onedrive is latest version.

Many times, even the taskbar icon showing as uptodate and no syncing is pending, this library is returning the status as Syncing.

This is occuring very commonly now a days.

**Comment by rodneyviana** [comment]
What do you get in your logs when you run with "-IncludeLog $true"?

**Comment by rodneyviana** [comment]
closing as it is idle for 28 days

**Comment by ukreddy-erwin** [comment]
THis isssue is not regular..Once in  whileI am getting this. ANd faced by many others. So, can't provide the logs immediately. Please reopen it
