### ISSUE TITLE
Impossible to load OneDriveLib.dll

### ISSUE THREAD

**Issue by fschettini-git** [rodneyviana/ODSyncService#16]
Hi,

I have dowloaded OneDriveLib.dll and run the 2 lines.

PS C:\temp\ODTool> unblock-File -Path OneDriveLib.dll
PS C:\temp\ODTool> Import-Module OneDriveLib.dll

But I got the following error:

Import-Module : Le module «OneDriveLib.dll» spécifié n'a pas été chargé, car aucun fichier de module valide n'a été
trouvé dans un répertoire de module.
Au caractère Ligne:1 : 1
+ Import-Module "OneDriveLib.dll"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (OneDriveLib.dll:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Could you please help me?

Thanks in advance.

**Comment by N0odlez** [comment]
Is the OneDriveLib.dll in the folder C:\tmp\ODTool?

Try Import-Module .\OneDriveLib.dll

**Comment by fschettini-git** [comment]
Great it works with .\OneDriveLib.dll

Thanks
