### ISSUE TITLE
OneDrive not detecing

### ISSUE THREAD

**Issue by ukreddy-erwin** [rodneyviana/ODSyncService#2]
OneDrive app is running in the tray.
But when we integrate this powershell command with Jenkins, it is giving status as "NotInstalled".
Jenkins slave is running as a current user only, not as system user.

**Comment by rodneyviana** [comment]
I put together a trace version of the DLL here: https://blogs.msdn.microsoft.com/rodneyviana/2017/08/30/tool-to-generate-debugdiag-rule-for-sharepoint-based-on-event-id-tag-and-optionally-a-partial-message/

Run it and paste the contents of %temp%\OneDriveLib-yyyy-mm-dd.log here. You can open the file with this command (from command prompt, not PowerShell)

notepad %temp%\OneDriveLib-yyyy-mm-dd.log

(replace yyyy per year, mm for month and dd for day.

For today 2/6/2018, the command would be:
notepad %temp%\OneDriveLib-2018-02-06.log

**Comment by prlpl** [comment]
I got 
2019-02-11T21:55:47	Information	Testing Type: Native.IIconGrooveError, Path: C:\

**Comment by rodneyviana** [comment]
I uploaded a new version at: https://github.com/rodneyviana/ODSyncService/tree/master/Binaries/PowerShell
