### ISSUE TITLE
BadImageFormatException - assembly manifest?

### ISSUE THREAD

**Issue by cyn3rgy** [rodneyviana/ODSyncService#20]
Hi I'm getting the following error when trying to import the module
import-module : Could not load file or assembly 'file:///C:\OndeDrive\OneDriveLib.dll' or one
of its dependencies. The module was expected to contain an assembly manifest.
At line:1 char:1
+ import-module C:\OneDrive\OneDriveLib.dll
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], BadImageFormatException
    + FullyQualifiedErrorId : System.BadImageFormatException,Microsoft.PowerShell.Commands.ImportModuleCommand

Wondering if you have seen this before?

**Comment by rodneyviana** [comment]
> Hi I'm getting the following error when trying to import the module
> import-module : Could not load file or assembly 'file:///C:\OndeDrive\OneDriveLib.dll' or one
> of its dependencies. The module was expected to contain an assembly manifest.
> At line:1 char:1
> 
> * import-module C:\OneDrive\OneDriveLib.dll
> * ```
>     + CategoryInfo          : NotSpecified: (:) [Import-Module], BadImageFormatException
>     + FullyQualifiedErrorId : System.BadImageFormatException,Microsoft.PowerShell.Commands.ImportModuleCommand
>   ```
> 
> Wondering if you have seen this before?

See this:
https://github.com/rodneyviana/ODSyncService/issues/5#issuecomment-573111391

**Comment by StevenReid** [comment]
I am getting the same result  and have followed the steps in #5

**Comment by cyn3rgy** [comment]
I ran the suggested script and re-ran the download. I'm getting the same file hash in the script and the download:
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          411FCC70A9AA76AA3403C196DA34433A16A65CB850154E5FFE5B72B42334D482

Is that correct?

**Comment by rodneyviana** [comment]
Is it happening on just a computer or on all computers?
It may be any of these:
- You copied the DLL to a protect folder (like c:\ or c:\Program Files). Copy it to a simple folder like c:\odsync\ which looks like you already did
- Your antivirus is targeting the DLL. Create an exclusion for the DLL on your anti-virus

**Comment by cyn3rgy** [comment]
My issue was resolved by using another computer for the download. It's curious that the issue isn't happening with other downloads. Also on e I downloaded it to another location, I could then copy the file to my main computer without issue. Very bizarre and I'm sure a source of frustration for you Rodney. Thanks for your support.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
