### ISSUE TITLE
Output Language

### ISSUE THREAD

**Issue by n3roGit** [rodneyviana/ODSyncService#26]
I noticed that the output of the status is different depending on the system language. This makes it difficult to check for different statuses.

Example:
LocalPath    : C:\Users\USERNAME\OneDrive
UserSID      : S-1-5-21-XXXXX
UserName     : DOMAIN\USER
DisplayName  : OneDrive
ServiceType  : Business1
**StatusString : Sie sind nicht angemeldet.**

I have already tried to set the output to English. Unfortunately without success.
Set-Culture -CultureInfo en-US
[cultureinfo]::CurrentUICulture = 'en-US'
Set-WinUILanguageOverride -Language en-us

Would it be possible to implement a status as a number here?

**Comment by rodneyviana** [comment]
Hi n3roGit:

For On Demand, unfortunately the statuses are not enumeration of types but what the application reads for the taskbar.  It uses the operating system language.
