### ISSUE TITLE
Taskbar refreshes when you call Get-ODStatus

### ISSUE THREAD

**Issue by yatesa** [rodneyviana/ODSyncService#4]
Is is possible to stop the taskbar refreshing when you call Get-ODStatus with Powershell.
We have a script that regularly runs and checks the OneDrive status but you keep seeing taskbar refresh each time. Not a major issue but just a bit annoying.

**Comment by rodneyviana** [comment]
The code would not (intentionally) cause any of this.

**Comment by meramkumartrn** [comment]
@rodneyviana, when the program executes the taskbar icon, are refreshed. Got any clue how to avoid.

**Comment by rodneyviana** [comment]
Are you talking about GetUnsynchedFiles()?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by meramkumartrn** [comment]
Nope Get-ODStatus

**Comment by meramkumartrn** [comment]
`
Import-Module "C:\Users\meramkumar\Desktop\OneDriveLib.dll" -Verbose


do { 
    
    $message = (Get-ODStatus –Type Business)| Where {$_.StatusString -eq 'Error'}
    If($message.StatusString -eq 'Error')
    {
        Write-Host (Get-Date).ToString(),$env:UserName,$env:COMPUTERNAME,$message.StatusString, $message.LocalPath, $message.ServerType
    }
    start-sleep -seconds 5 
} until($x -eq 1)

`

**Comment by meramkumartrn** [comment]
@rodneyviana try the above code you will see when the folder has an error. to test it create a folder "forms" inside the one drive.

**Comment by rodneyviana** [comment]
This should not happen unless you have a large number of OneDrive connections or are using -ByPath.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by rodneyviana** [comment]
In this loop situation this is a possibility.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by meramkumartrn** [comment]
@rodneyviana Got it I will try to schedule via windows scheduler.

**Comment by srzelic** [comment]
I have the same issue.. Any resolution?

**Comment by rodneyviana** [comment]
This is by design. See the workarounds in the thread.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by srzelic** [comment]
Maybe I'm blind but I don't see any workaround in this thread? I'm not using -bypath or two many connection (2-5).

**Comment by srzelic** [comment]
Anyone resolved this issue?

**Comment by meramkumartrn** [comment]
There is no solution I did by running the code every hour. always it flicks the screen for a second.

**Comment by srzelic** [comment]
We did the same but all users are complaining and taskbar flickers several times. Rodneyviana mentioned that there is a workaround in thread but I don't see it.

**Comment by rodneyviana** [comment]
The workaround is not to run with -ByPath and only once an hour.

**Comment by N0odlez** [comment]
Sorry to drag this one back up again but there must be a solution to stop what ever is causing the taskbar to refresh? I personally believe it to be an issue with the cpp files as nothing in the CSharp sticks out to me as causing the issue. Please can we relook in to this as I'm sure solving this issue will help a LOT of people
