### ISSUE TITLE
OneDriveLib.dll not working with 1903

### ISSUE THREAD

**Issue by dprice116** [rodneyviana/ODSyncService#6]
I have setup a powershell script to run OneDriveLib.dll and get status on our OneDrive libraries. On 1903 builds, the dll will import, but get a NullReferenceException when running Get-ODStatus. This works on 1809 and lower builds. Details:

get-odstatus : Object reference not set to an instance of an object.
At line:1 char:1
+ get-odstatus
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ODStatus], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,OneDriveLib.GetStatus

**Comment by dprice116** [comment]
My bad, it 1903, not 1809

**Comment by dprice116** [comment]
Forgot to mention that the version of OneDrive is the same on both systems: 19.123.0624.0005

**Comment by rodneyviana** [comment]
I could reproduce the problem. I will check what the problem is.

**Comment by dprice116** [comment]
Thanks for that. After a lot of trail and error, I managed to get it working with Windows 10 Pro Education 1903. Windows 10 Education 1903 still does not work.

**Comment by rodneyviana** [comment]
I could not reproduce actually.   I tried the wrong version. I tested with Windows 10.0.18990.1 and I am enrolled in Windows Insider program fast track. What do you get in cmd prompt when you run: "ver"?
```
C:\Windows\System32>ver

Microsoft Windows [Version 10.0.18990.1]
```

**Comment by Niclash1979** [comment]
Hi. Found this today and saw that only a clean installed 1903 of windows 10 is affected on another forum

**Comment by dprice116** [comment]
Sorry for the delay, My test computer is using:
Version 10.0.18362.30

**Comment by RobinBeismann** [comment]
Can reproduce it on Build 18362.175, fails with an assembly missing error.

**Comment by rodneyviana** [comment]
Check the new version
